---
  - name: install certbot
    block:
      - name: Make sure pip is latest
        pip:
          name: pip
          state: latest

      - name: Install certbot with certbot-nginx,certbot-route53,certbot-dns-route53 plugins
        pip:
          name: ['certbot','certbot-nginx','certbot-route53','certbot-dns-route53', 'cryptography>=2.3']
          state: latest

      - name: Generate SSL
        shell: certbot certonly --dns-route53 --agree-tos --non-interactive -d {{ jenkins_dns_record }} --email jenkins-dev@domain.com

      - name: ensure www-data can read the certificates
        file:
          path: "{{ item }}"
          group: www-data
        with_items:
          - "{{ letsencrypt_live_base_path }}{{ jenkins_dns_record }}/fullchain.pem"
          - "{{ letsencrypt_live_base_path }}{{ jenkins_dns_record }}/privkey.pem"

      - name: create auto-renew task
        cron:
          name: "certbot auto renew"
          job: "certbot renew --non-interactive --post-hook 'service nginx reload'"
          day: 1
          hour: 3

  - name: jenkins site setup with a certbot certificate
    block:
      - name: concate certificates (avoid errors with curl)
        shell: bash -c "cat {{letsencrypt_live_base_path}}{{ jenkins_dns_record }}/{cert*.pem,chain*.pem,fullchain*.pem} > {{letsencrypt_live_base_path}}{{ jenkins_dns_record }}/concated_cert.pem"

      - name: template nginx jenkins site
        template:
          src: templates/jenkins_certbot.j2
          dest: /etc/nginx/sites-available/jenkins.conf
          group: www-data
          mode: 0770

    become: true